version: '3.8'

services:
  terminal:
    image: goddamnman/ros_humble_gazebo_fortress:v0.0.2
    container_name: ros_fortress
    network_mode: host
    privileged: true
    volumes:
      - .:/home/ros_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    shm_size: 2gb
    stdin_open: true
    tty: true

    user: "mobile"